import Head from 'next/head'
import styles from 'styles/Home.module.css'
import ProductVoucherForm from 'components/ProductVoucherForm';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Optimization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ProductVoucherForm />
      </main>
    </div>
  )
}

export default Home
